### ISSUE TITLE
Add rounding helpers

### ISSUE THREAD

**Issue by gabriel-pinheiro** [gabriel-pinheiro/bigodon#10]
**Helper description**
There are no helpers for converting between floats and integers like floor, ceil, round or toFixed

**Examples**
```hbs
{{toFixed 5 2}} {{! should return "5.00" }}
{{toFixed 3.14159265 2}} {{! should return "3.14" }}
{{floor 5.9}} {{! should return 5 }}
{{ceil 5.1}} {{! should return 6 }}
{{round 5.1}} {{! should return 5}}
{{round 5.9}} {{!should return 6}}
```

## Do you want to contribute?
If you wish to contribute, please send us a PR including this helper's implementation, just tests or both! Take a look at [how to clone Bigodon for contributing](https://github.com/gabriel-pinheiro/bigodon/blob/main/CONTRIBUTING.md#cloning-bigodon), at [how a similar helper is implemented](https://github.com/gabriel-pinheiro/bigodon/blob/main/src/runner/helpers/math.ts#L5-L7) and [how it's tested](https://github.com/gabriel-pinheiro/bigodon/blob/main/test/math-helpers.spec.js#L41-L64).

[Here](https://github.com/gabriel-pinheiro/bigodon/commit/dc36a5a5a73c2fe142d403c0bf56aa93caf92d43) is a commit implementing another operator that might be useful.

**If you want to give this a shot, make sure to comment here to avoid duplicates**

**Comment by nmarulo** [comment]
Hello, can I try to make this one?

**Comment by gabriel-pinheiro** [comment]
@nmarulo sure! I just assigned it to you! Feel free to [email](mailto:o54b27nq0oasp75z5mwr44a4vur17bgp@owlmail.io) or [DM](https://twitter.com/NotNull_gabriel) me if you have any questions 😄
