### ISSUE TITLE
Add sort helper for arrays

### ISSUE THREAD

**Issue by SnehaNarendran01071998** [gabriel-pinheiro/bigodon#20]
**Helper description**
A helper that would sort the array of strings and numbers. 
This would be a wrapper around Array.sort(). 
It would sort in ascending order by default. On passing a flag, it would sort in descending order.
For string, the sort would be based on the first character of the string. 

**Usage**
For Descending Order: 
const source = `{{join (sort arr desc) ", "}}`;
const templ = compile(source);
const result =  await templ({ arr: [12, -9, -100, 67], desc:true});

**Examples**
Array: [12, -9, -100, 67]
```hbs
O/P(ascending): -100, -9, 12, 67
```
Array: ["Banana", "Orange", "Apple", "Mango"]
```hbs
O/P(descending): Orange, Mango, Banana, Apple
```

**Comment by gabriel-pinheiro** [comment]
Added on #21 , thank you again 😄
