### ISSUE TITLE
Add isEmpty helper

### ISSUE THREAD

**Issue by gabriel-pinheiro** [gabriel-pinheiro/bigodon#8]
**Helper description**
A helper that would tell if an array or string is empty.

**Examples**
```hbs
{{! Instead of writing this }}
{{#is (length arr) 0}}
The array is empty!
{{/is}}

{{! This would be better }}
{{#isEmpty arr}}
The array is empty!
{{/isEmpty}}

{{! For tests, this would return true or false }}
{{isEmpty arr}}
```

## Do you want to contribute?
If you wish to contribute, please send us a PR including this helper's implementation, just tests or both! Take a look at [how to clone Bigodon for contributing](https://github.com/gabriel-pinheiro/bigodon/blob/main/CONTRIBUTING.md#cloning-bigodon), at [how a similar helper is implemented](https://github.com/gabriel-pinheiro/bigodon/blob/main/src/runner/helpers/array.ts#L30-L36) and [how it's tested](https://github.com/gabriel-pinheiro/bigodon/blob/main/test/array-helpers.spec.js#L77-L97).

**Comment by soumyo123-prog** [comment]
Can I work on this?

**Comment by gabriel-pinheiro** [comment]
@soumyo123-prog sure, I just assigned it to you! Feel free to [email](mailto:o54b27nq0oasp75z5mwr44a4vur17bgp@owlmail.io) or [DM](https://twitter.com/NotNull_gabriel) me if you have any questions 😄
