### ISSUE TITLE
More math operation helpers

### ISSUE THREAD

**Issue by gabriel-pinheiro** [gabriel-pinheiro/bigodon#9]
**Helper description**
Helpers like multiply/times, divide, modulus/modulo/mod/remainder

**Examples**
```hbs
{{! These already exist }}
2 + 3 is {{add 2 3}}
8 - 5 is {{subtract 8 5}}

{{! These are missing }}
5 x 3 is {{multiply 5 3}}
8 / 2 is {{divide 8 2}}
5 % 2 is {{mod 5 2}}
```

## Do you want to contribute?
If you wish to contribute, please send us a PR including this helper's implementation, just tests or both! Take a look at [how to clone Bigodon for contributing](https://github.com/gabriel-pinheiro/bigodon/blob/main/CONTRIBUTING.md#cloning-bigodon), at [how a similar helper is implemented](https://github.com/gabriel-pinheiro/bigodon/blob/main/src/runner/helpers/math.ts#L5-L7) and [how it's tested](https://github.com/gabriel-pinheiro/bigodon/blob/main/test/math-helpers.spec.js#L41-L64).

[Here](https://github.com/gabriel-pinheiro/bigodon/commit/dc36a5a5a73c2fe142d403c0bf56aa93caf92d43) is a commit implementing another operator that might be useful.

**If you want to give this a shot, make sure to comment here to avoid duplicates**

**Comment by namitaarya** [comment]
Can I take up this issue?

**Comment by gabriel-pinheiro** [comment]
@namitaarya sure! I just assigned it to you! Feel free to [email](mailto:o54b27nq0oasp75z5mwr44a4vur17bgp@owlmail.io) or [DM](https://twitter.com/NotNull_gabriel) me if you have any questions 😄
